name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_env:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install DEP
      run: sudo apt install -y build-essential cmake pkg-config automake autoconf libtool unzip libxcursor-dev libglu1-mesa-dev libpulse-dev libasound2-dev libpng-dev mingw-w64-x86-64-dev gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
    
    - name: Install Qt
      # You may pin to the exact commit or the version.
      # uses: jurplel/install-qt-action@2d518188e746defd451af981c3c901f463d99e29
      uses: jurplel/install-qt-action@v3.2.1
    
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build DEP
      run: cd ./src/libacfutils && ./build_deps

    - name: Build libacfutils
      run: cd ./src/libacfutils/qmake && ./build-win-lin

    - name: Build
      # Build your program with the given configuration
      run: ./build_release

