name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install MinGW
      # You may pin to the exact commit or the version.
      # uses: egor-tensin/setup-mingw@84c781b557efd538dec66bde06988d81cd3138cf
      uses: egor-tensin/setup-mingw@v2
    
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      # Build your program with the given configuration
      run: ./build_release

